[package]
name = "twilight"
version = "0.1.0"
edition = "2021"

[dependencies]
capnp = "0.14.9"

[dependencies.windows]
version = "0.40.0"
features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_HiDpi",
]
