[package]
name = "twilight"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.38"
anyhow = "1.0.68"
capnp = "0.16.0"
tokio = { version = "1.25.0", features = ["full"] }
winit = "0.27.5"
wgpu = "0.15.0"
env_logger = "0.10.0"
flatbuffers = "23.1.21"
pollster = "0.2.5"
cfg-if = "1.0.0"

[dependencies.windows]
version = "0.43.0"
features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_HiDpi",
]

[profile.dev]
opt-level = 1
