[package]
name = "twilight"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.35"
anyhow = "1.0.65"
capnp = "0.14.9"
tokio = { version = "1.21.2", features = ["full"] }
winit = "0.27.3"
wgpu = "0.14.0"
pollster = "0.2.5"

[dependencies.windows]
version = "0.40.0"
features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_HiDpi",
]
