// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

#[allow(unused_imports, dead_code)]
pub mod video {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};

#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_VIDEO_CODEC: i8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_VIDEO_CODEC: i8 = 2;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_VIDEO_CODEC: [VideoCodec; 3] = [
  VideoCodec::Empty,
  VideoCodec::Bgra8888,
  VideoCodec::Rgb24,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct VideoCodec(pub i8);
#[allow(non_upper_case_globals)]
impl VideoCodec {
  pub const Empty: Self = Self(0);
  pub const Bgra8888: Self = Self(1);
  pub const Rgb24: Self = Self(2);

  pub const ENUM_MIN: i8 = 0;
  pub const ENUM_MAX: i8 = 2;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::Empty,
    Self::Bgra8888,
    Self::Rgb24,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::Empty => Some("Empty"),
      Self::Bgra8888 => Some("Bgra8888"),
      Self::Rgb24 => Some("Rgb24"),
      _ => None,
    }
  }
}
impl core::fmt::Debug for VideoCodec {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> flatbuffers::Follow<'a> for VideoCodec {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = flatbuffers::read_scalar_at::<i8>(buf, loc);
    Self(b)
  }
}

impl flatbuffers::Push for VideoCodec {
    type Output = VideoCodec;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        flatbuffers::emplace_scalar::<i8>(dst, self.0);
    }
}

impl flatbuffers::EndianScalar for VideoCodec {
  type Scalar = i8;
  #[inline]
  fn to_little_endian(self) -> i8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: i8) -> Self {
    let b = i8::from_le(v);
    Self(b)
  }
}

impl<'a> flatbuffers::Verifiable for VideoCodec {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    i8::run_verifier(v, pos)
  }
}

impl flatbuffers::SimpleToVerifyInSlice for VideoCodec {}
pub enum EmptyTableOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct EmptyTable<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for EmptyTable<'a> {
  type Inner = EmptyTable<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> EmptyTable<'a> {

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    EmptyTable { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    _args: &'args EmptyTableArgs
  ) -> flatbuffers::WIPOffset<EmptyTable<'bldr>> {
    let mut builder = EmptyTableBuilder::new(_fbb);
    builder.finish()
  }

}

impl flatbuffers::Verifiable for EmptyTable<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .finish();
    Ok(())
  }
}
pub struct EmptyTableArgs {
}
impl<'a> Default for EmptyTableArgs {
  #[inline]
  fn default() -> Self {
    EmptyTableArgs {
    }
  }
}

pub struct EmptyTableBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> EmptyTableBuilder<'a, 'b> {
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> EmptyTableBuilder<'a, 'b> {
    let start = _fbb.start_table();
    EmptyTableBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<EmptyTable<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for EmptyTable<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("EmptyTable");
      ds.finish()
  }
}
pub enum NotifyVideoStartOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct NotifyVideoStart<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for NotifyVideoStart<'a> {
  type Inner = NotifyVideoStart<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> NotifyVideoStart<'a> {
  pub const VT_WIDTH: flatbuffers::VOffsetT = 4;
  pub const VT_HEIGHT: flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    NotifyVideoStart { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args NotifyVideoStartArgs
  ) -> flatbuffers::WIPOffset<NotifyVideoStart<'bldr>> {
    let mut builder = NotifyVideoStartBuilder::new(_fbb);
    builder.add_height(args.height);
    builder.add_width(args.width);
    builder.finish()
  }


  #[inline]
  pub fn width(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(NotifyVideoStart::VT_WIDTH, Some(0)).unwrap()}
  }
  #[inline]
  pub fn height(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(NotifyVideoStart::VT_HEIGHT, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for NotifyVideoStart<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<u32>("width", Self::VT_WIDTH, false)?
     .visit_field::<u32>("height", Self::VT_HEIGHT, false)?
     .finish();
    Ok(())
  }
}
pub struct NotifyVideoStartArgs {
    pub width: u32,
    pub height: u32,
}
impl<'a> Default for NotifyVideoStartArgs {
  #[inline]
  fn default() -> Self {
    NotifyVideoStartArgs {
      width: 0,
      height: 0,
    }
  }
}

pub struct NotifyVideoStartBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> NotifyVideoStartBuilder<'a, 'b> {
  #[inline]
  pub fn add_width(&mut self, width: u32) {
    self.fbb_.push_slot::<u32>(NotifyVideoStart::VT_WIDTH, width, 0);
  }
  #[inline]
  pub fn add_height(&mut self, height: u32) {
    self.fbb_.push_slot::<u32>(NotifyVideoStart::VT_HEIGHT, height, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> NotifyVideoStartBuilder<'a, 'b> {
    let start = _fbb.start_table();
    NotifyVideoStartBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<NotifyVideoStart<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for NotifyVideoStart<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("NotifyVideoStart");
      ds.field("width", &self.width());
      ds.field("height", &self.height());
      ds.finish()
  }
}
pub enum VideoFrameOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct VideoFrame<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for VideoFrame<'a> {
  type Inner = VideoFrame<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> VideoFrame<'a> {
  pub const VT_VIDEO_BYTES: flatbuffers::VOffsetT = 4;
  pub const VT_CURSOR_UPDATE: flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    VideoFrame { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args VideoFrameArgs<'args>
  ) -> flatbuffers::WIPOffset<VideoFrame<'bldr>> {
    let mut builder = VideoFrameBuilder::new(_fbb);
    builder.add_video_bytes(args.video_bytes);
    if let Some(x) = args.cursor_update { builder.add_cursor_update(x); }
    builder.finish()
  }


  #[inline]
  pub fn video_bytes(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(VideoFrame::VT_VIDEO_BYTES, Some(0)).unwrap()}
  }
  #[inline]
  pub fn cursor_update(&self) -> Option<CursorUpdate<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<CursorUpdate>>(VideoFrame::VT_CURSOR_UPDATE, None)}
  }
}

impl flatbuffers::Verifiable for VideoFrame<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<u64>("video_bytes", Self::VT_VIDEO_BYTES, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<CursorUpdate>>("cursor_update", Self::VT_CURSOR_UPDATE, false)?
     .finish();
    Ok(())
  }
}
pub struct VideoFrameArgs<'a> {
    pub video_bytes: u64,
    pub cursor_update: Option<flatbuffers::WIPOffset<CursorUpdate<'a>>>,
}
impl<'a> Default for VideoFrameArgs<'a> {
  #[inline]
  fn default() -> Self {
    VideoFrameArgs {
      video_bytes: 0,
      cursor_update: None,
    }
  }
}

pub struct VideoFrameBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> VideoFrameBuilder<'a, 'b> {
  #[inline]
  pub fn add_video_bytes(&mut self, video_bytes: u64) {
    self.fbb_.push_slot::<u64>(VideoFrame::VT_VIDEO_BYTES, video_bytes, 0);
  }
  #[inline]
  pub fn add_cursor_update(&mut self, cursor_update: flatbuffers::WIPOffset<CursorUpdate<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<CursorUpdate>>(VideoFrame::VT_CURSOR_UPDATE, cursor_update);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> VideoFrameBuilder<'a, 'b> {
    let start = _fbb.start_table();
    VideoFrameBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<VideoFrame<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for VideoFrame<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("VideoFrame");
      ds.field("video_bytes", &self.video_bytes());
      ds.field("cursor_update", &self.cursor_update());
      ds.finish()
  }
}
pub enum CursorUpdateOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct CursorUpdate<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for CursorUpdate<'a> {
  type Inner = CursorUpdate<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> CursorUpdate<'a> {
  pub const VT_SHAPE: flatbuffers::VOffsetT = 4;
  pub const VT_X: flatbuffers::VOffsetT = 6;
  pub const VT_Y: flatbuffers::VOffsetT = 8;
  pub const VT_VISIBLE: flatbuffers::VOffsetT = 10;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    CursorUpdate { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args CursorUpdateArgs<'args>
  ) -> flatbuffers::WIPOffset<CursorUpdate<'bldr>> {
    let mut builder = CursorUpdateBuilder::new(_fbb);
    builder.add_y(args.y);
    builder.add_x(args.x);
    if let Some(x) = args.shape { builder.add_shape(x); }
    builder.add_visible(args.visible);
    builder.finish()
  }


  #[inline]
  pub fn shape(&self) -> Option<CursorShape<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<CursorShape>>(CursorUpdate::VT_SHAPE, None)}
  }
  #[inline]
  pub fn x(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(CursorUpdate::VT_X, Some(0)).unwrap()}
  }
  #[inline]
  pub fn y(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(CursorUpdate::VT_Y, Some(0)).unwrap()}
  }
  #[inline]
  pub fn visible(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(CursorUpdate::VT_VISIBLE, Some(false)).unwrap()}
  }
}

impl flatbuffers::Verifiable for CursorUpdate<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<CursorShape>>("shape", Self::VT_SHAPE, false)?
     .visit_field::<u32>("x", Self::VT_X, false)?
     .visit_field::<u32>("y", Self::VT_Y, false)?
     .visit_field::<bool>("visible", Self::VT_VISIBLE, false)?
     .finish();
    Ok(())
  }
}
pub struct CursorUpdateArgs<'a> {
    pub shape: Option<flatbuffers::WIPOffset<CursorShape<'a>>>,
    pub x: u32,
    pub y: u32,
    pub visible: bool,
}
impl<'a> Default for CursorUpdateArgs<'a> {
  #[inline]
  fn default() -> Self {
    CursorUpdateArgs {
      shape: None,
      x: 0,
      y: 0,
      visible: false,
    }
  }
}

pub struct CursorUpdateBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> CursorUpdateBuilder<'a, 'b> {
  #[inline]
  pub fn add_shape(&mut self, shape: flatbuffers::WIPOffset<CursorShape<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<CursorShape>>(CursorUpdate::VT_SHAPE, shape);
  }
  #[inline]
  pub fn add_x(&mut self, x: u32) {
    self.fbb_.push_slot::<u32>(CursorUpdate::VT_X, x, 0);
  }
  #[inline]
  pub fn add_y(&mut self, y: u32) {
    self.fbb_.push_slot::<u32>(CursorUpdate::VT_Y, y, 0);
  }
  #[inline]
  pub fn add_visible(&mut self, visible: bool) {
    self.fbb_.push_slot::<bool>(CursorUpdate::VT_VISIBLE, visible, false);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> CursorUpdateBuilder<'a, 'b> {
    let start = _fbb.start_table();
    CursorUpdateBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<CursorUpdate<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for CursorUpdate<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("CursorUpdate");
      ds.field("shape", &self.shape());
      ds.field("x", &self.x());
      ds.field("y", &self.y());
      ds.field("visible", &self.visible());
      ds.finish()
  }
}
pub enum CursorShapeOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct CursorShape<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for CursorShape<'a> {
  type Inner = CursorShape<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> CursorShape<'a> {
  pub const VT_IMAGE: flatbuffers::VOffsetT = 4;
  pub const VT_CODEC: flatbuffers::VOffsetT = 6;
  pub const VT_XOR: flatbuffers::VOffsetT = 8;
  pub const VT_HOTSPOTX: flatbuffers::VOffsetT = 10;
  pub const VT_HOTSPOTY: flatbuffers::VOffsetT = 12;
  pub const VT_WIDTH: flatbuffers::VOffsetT = 14;
  pub const VT_HEIGHT: flatbuffers::VOffsetT = 16;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    CursorShape { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args CursorShapeArgs<'args>
  ) -> flatbuffers::WIPOffset<CursorShape<'bldr>> {
    let mut builder = CursorShapeBuilder::new(_fbb);
    builder.add_height(args.height);
    builder.add_width(args.width);
    builder.add_hotspoty(args.hotspoty);
    builder.add_hotspotx(args.hotspotx);
    if let Some(x) = args.image { builder.add_image(x); }
    builder.add_xor(args.xor);
    builder.add_codec(args.codec);
    builder.finish()
  }


  #[inline]
  pub fn image(&self) -> Option<flatbuffers::Vector<'a, u8>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u8>>>(CursorShape::VT_IMAGE, None)}
  }
  #[inline]
  pub fn codec(&self) -> VideoCodec {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<VideoCodec>(CursorShape::VT_CODEC, Some(VideoCodec::Empty)).unwrap()}
  }
  #[inline]
  pub fn xor(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(CursorShape::VT_XOR, Some(false)).unwrap()}
  }
  #[inline]
  pub fn hotspotx(&self) -> f32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(CursorShape::VT_HOTSPOTX, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn hotspoty(&self) -> f32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(CursorShape::VT_HOTSPOTY, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn width(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(CursorShape::VT_WIDTH, Some(0)).unwrap()}
  }
  #[inline]
  pub fn height(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(CursorShape::VT_HEIGHT, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for CursorShape<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u8>>>("image", Self::VT_IMAGE, false)?
     .visit_field::<VideoCodec>("codec", Self::VT_CODEC, false)?
     .visit_field::<bool>("xor", Self::VT_XOR, false)?
     .visit_field::<f32>("hotspotx", Self::VT_HOTSPOTX, false)?
     .visit_field::<f32>("hotspoty", Self::VT_HOTSPOTY, false)?
     .visit_field::<u32>("width", Self::VT_WIDTH, false)?
     .visit_field::<u32>("height", Self::VT_HEIGHT, false)?
     .finish();
    Ok(())
  }
}
pub struct CursorShapeArgs<'a> {
    pub image: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u8>>>,
    pub codec: VideoCodec,
    pub xor: bool,
    pub hotspotx: f32,
    pub hotspoty: f32,
    pub width: u32,
    pub height: u32,
}
impl<'a> Default for CursorShapeArgs<'a> {
  #[inline]
  fn default() -> Self {
    CursorShapeArgs {
      image: None,
      codec: VideoCodec::Empty,
      xor: false,
      hotspotx: 0.0,
      hotspoty: 0.0,
      width: 0,
      height: 0,
    }
  }
}

pub struct CursorShapeBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> CursorShapeBuilder<'a, 'b> {
  #[inline]
  pub fn add_image(&mut self, image: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(CursorShape::VT_IMAGE, image);
  }
  #[inline]
  pub fn add_codec(&mut self, codec: VideoCodec) {
    self.fbb_.push_slot::<VideoCodec>(CursorShape::VT_CODEC, codec, VideoCodec::Empty);
  }
  #[inline]
  pub fn add_xor(&mut self, xor: bool) {
    self.fbb_.push_slot::<bool>(CursorShape::VT_XOR, xor, false);
  }
  #[inline]
  pub fn add_hotspotx(&mut self, hotspotx: f32) {
    self.fbb_.push_slot::<f32>(CursorShape::VT_HOTSPOTX, hotspotx, 0.0);
  }
  #[inline]
  pub fn add_hotspoty(&mut self, hotspoty: f32) {
    self.fbb_.push_slot::<f32>(CursorShape::VT_HOTSPOTY, hotspoty, 0.0);
  }
  #[inline]
  pub fn add_width(&mut self, width: u32) {
    self.fbb_.push_slot::<u32>(CursorShape::VT_WIDTH, width, 0);
  }
  #[inline]
  pub fn add_height(&mut self, height: u32) {
    self.fbb_.push_slot::<u32>(CursorShape::VT_HEIGHT, height, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> CursorShapeBuilder<'a, 'b> {
    let start = _fbb.start_table();
    CursorShapeBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<CursorShape<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for CursorShape<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("CursorShape");
      ds.field("image", &self.image());
      ds.field("codec", &self.codec());
      ds.field("xor", &self.xor());
      ds.field("hotspotx", &self.hotspotx());
      ds.field("hotspoty", &self.hotspoty());
      ds.field("width", &self.width());
      ds.field("height", &self.height());
      ds.finish()
  }
}
}  // pub mod video

